// icons/Icon_Helper.js
import {
  FaArrowUp, FaArrowRight, FaWhatsapp, FaEnvelope, FaPhone,
  FaBars, FaTimes, FaFacebook, FaInstagram, FaLinkedin,
  FaTwitter, FaYoutube, FaGithub, FaClock, FaCog,
  FaChartLine, FaIndustry, FaStar, FaGlobe, FaRocket,
  FaSatellite, FaMeteor, FaFire, FaShieldAlt, FaHeadset,
  FaFacebookF, FaPhoneAlt, FaMapMarkerAlt, FaHeart, FaCode,
  FaPaintBrush, FaLaptopCode,
  FaCodeBranch,
  FaServer,
  FaTools,
  FaLightbulb,
  FaMicrochip,
  FaBolt, FaDatabase,
  FaReact, FaNodeJs, FaPython, FaJava, FaAws, FaDocker,
  FaCrown, FaHandshake,
  FaTrophy,
  FaUserTie,
  FaPaperPlane,
  FaCheckCircle,
  FaMobile, FaPalette, FaCloud, FaRobot, FaShoppingCart,
  FaChevronRight, FaCogs,
  FaChevronLeft,
  FaAward,
  FaUsers,
  FaGlobeAmericas,
  FaRegClock,
  FaInfinity,
  FaBrain,
  FaEye,
  FaNetworkWired,
  FaMobileAlt,
  FaBullhorn,
  FaFingerprint,
  FaEnvelopeOpenText, FaCheck,
  FaRedo,
  FaSearch,
  FaExchangeAlt,
  FaPlay,
  FaPause,
  FaArrowLeft,
} from "react-icons/fa";
import { CiSettings } from "react-icons/ci";
import { SiMinutemailer } from "react-icons/si";
import { MdOutlineStarRate } from "react-icons/md";
import { AiOutlineDoubleRight } from "react-icons/ai";

const Icon_Helper = Object.freeze({
  FaArrowUp, FaRedo,
  FaSearch,
  FaExchangeAlt,
  FaPlay,
  FaPause,
  FaArrowLeft,
  FaArrowRight,
  FaWhatsapp,
  FaEnvelope,
  FaPhone,
  FaBars,
  FaTimes,
  FaFacebook,
  FaInstagram,
  FaLinkedin,
  FaTwitter,
  FaYoutube,
  FaGithub, FaClock, FaCog, FaChartLine, FaIndustry, FaStar, FaGlobe, FaRocket, FaSatellite,
  FaMeteor, FaFire, FaShieldAlt, FaHeadset, FaFacebookF, FaPhoneAlt, FaMapMarkerAlt, FaHeart, FaCode,
  FaPaintBrush,
  SiMinutemailer,
  FaLaptopCode,
  FaCodeBranch,
  FaServer,
  FaTools,
  FaLightbulb,
  FaMicrochip,
  FaBolt, FaDatabase,
  FaReact, FaNodeJs, FaPython, FaJava, FaAws, FaDocker,
  FaCrown, FaHandshake, FaTrophy,
  FaUserTie,
  FaPaperPlane,
  FaCheckCircle,
  FaMobile, FaPalette, FaCloud, FaRobot, FaShoppingCart,
  FaChevronRight, FaCogs,
  CiSettings, MdOutlineStarRate,
  FaChevronLeft, FaAward, AiOutlineDoubleRight, FaEnvelopeOpenText, FaCheck, FaUsers, FaGlobeAmericas, FaRegClock, FaInfinity,
  FaBrain, FaEye, FaNetworkWired, FaMobileAlt, FaBullhorn, FaFingerprint,

});

export default Icon_Helper;